name: My first github actions workflow

on: push

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: welcome mesage
        run: |
         echo "Hey, welcome to my githubu actions first workflow"
         ls -ltra
         cat README.md
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt


