name: My first github actions workflow

on: push

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: welcome mesage
          run: echo "Hey, welcome to my githubu actions first workflow"
        - name: list files
          run: ls
        - name: Please read the files
          run: cat README.md
