name: variablkes and secrects

on: push

jobs:
    docker_job:
        env:
            DOCKER_REGISTRY: docker.io
            IMAGE_NAME: Github-actions-nginx
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t $DOCKER_REGISTRY/${{ vars. DOCKER_USERNAME}}/$IMAGE_NAME:latest

            - name: Docker login
              run: echo docker login --username=${{ vars.DOCKER_USERNAME}} --password=${{ secrets.DOCKER_PASSWORD}}
            
            - name: Docker publish $DOCKER_REGISTRY/${{ vars. DOCKER_USERNAME}}/$IMAGE_NAME:latest
              run: echo docker push
    deploy:
        if: github.ref == 'refs/heads/main'
        env:
            DOCKER_REGISTRY: docker.io
            DOCKER_USERNMAE: pstr3355
            IMAGE_NAME: Github-actions-nginx
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $DOCKER_REGISTRY/${{ secrets.DOCKER_USERNAME}}/$IMAGE_NAME:latest