name: Assigning varaiables and secrets to workflow,job,steps levels

on: 
    push

jobs:
    docker: 
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: pstr3355
                IMAGE_NAME: github-actions-nginx

              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              env:
                DOCKER_PASSWORD: Ammanana@143
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            
            - name: Docker publish
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: pstr3355
                IMAGE_NAME: github-actions-nginx
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
