###### VARIABLES ASSIGNING AT WORKFLOW LEVEL##########
name: variablkes and secrects

on: push

env:
   DOCKER_REGISTRY: docker.io
   DOCKER_USERNMAE: pstr3355
   IMAGE_NAME: Github-actions-nginx
jobs:
    docker_job:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              env:
                DOCKER_PASSWORD: Ammanana@143
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            
            - name: Docker publish
              run: echo docker push
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest