name: workflow-dispatch-inputs

on:
    workflow_dispatch: 
        inputs:
         run-tests:
            description: "Run tests?"
            type: boolean
            required: true
         test-type:
            description: "Type of tests to run"
            type: choice
            options:
               - unit
               - integration
               - all
            required: true
         environment:
            description: "Choose an environment"
            type: environment
            required: true
         build-number:
            description: "custom build number"
            type: number
            required: false
         message:
            description: "Additional message"
            type: string
            required: false

jobs:
    build-and-deploy:
        runs-on: windows-latest
        steps:
           - name: Print workflow inputs
             run: |
                echo "Run tests: ${{inputs.run-tests}}"
                echo "Test type: ${{inputs.test-type}}"
                echo "Build number: ${{inputs.build-number}}"
                echo "message: ${{inputs.message}}"
           - name: Run tests
             if: ${{inputs.run-tests == 'true'}}
             run: echo "Testing.............."



            